/**
 * Legal Document Generation Service
 * Generates standard business formation documents
 */

export interface BusinessInfo {
  organizationName: string
  organizationType: 'LLC' | 'C-Corp' | 'S-Corp'
  state: string
  founderName: string
  founderEmail: string
  industry: string
  description: string
  formationDate?: Date
}

export interface DocumentTemplate {
  type: 'privacy-policy' | 'terms-of-service' | 'operating-agreement' | 'articles-of-incorporation'
  title: string
  content: string
  lastUpdated: Date
}

export class LegalDocumentGenerator {
  private static templates: Map<string, DocumentTemplate> = new Map()

  static generatePrivacyPolicy(businessInfo: BusinessInfo): DocumentTemplate {
    const content = `
# Privacy Policy for ${businessInfo.organizationName}

**Effective Date:** ${new Date().toLocaleDateString()}

## 1. Information We Collect

We collect information you provide directly to us, such as when you:
- Create an account or use our services
- Contact us for support
- Subscribe to our newsletters or marketing communications

### Personal Information
- Name and contact information (email address, phone number)
- Account credentials and preferences
- Payment and billing information
- Communication records and preferences

### Automatically Collected Information
- Device and browser information
- IP address and location data
- Usage patterns and service interactions
- Cookies and similar tracking technologies

## 2. How We Use Your Information

We use your information to:
- Provide, maintain, and improve our services
- Process transactions and send related information
- Send technical notices, security alerts, and support messages
- Respond to your comments, questions, and customer service requests
- Communicate with you about products, services, and events

## 3. Information Sharing and Disclosure

We do not sell, trade, or otherwise transfer your personal information to third parties except:
- With your explicit consent
- To comply with legal obligations
- To protect our rights and safety
- With service providers who assist in our operations

## 4. Data Security

We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.

## 5. Your Rights and Choices

You have the right to:
- Access, update, or delete your personal information
- Opt-out of marketing communications
- Request data portability
- File complaints with regulatory authorities

## 6. Data Retention

We retain your personal information for as long as necessary to provide our services and fulfill the purposes outlined in this policy, unless a longer retention period is required by law.

## 7. International Data Transfers

If you are accessing our services from outside the United States, please be aware that your information may be transferred to, stored, and processed in the United States.

## 8. Children's Privacy

Our services are not intended for children under 13. We do not knowingly collect personal information from children under 13.

## 9. Changes to This Policy

We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the effective date.

## 10. Contact Us

If you have any questions about this Privacy Policy, please contact us at:

**${businessInfo.organizationName}**
Email: ${businessInfo.founderEmail}

---

*This privacy policy was generated by Maverick's legal document system and should be reviewed by a qualified attorney to ensure compliance with applicable laws and regulations.*
`

    return {
      type: 'privacy-policy',
      title: `Privacy Policy - ${businessInfo.organizationName}`,
      content,
      lastUpdated: new Date()
    }
  }

  static generateTermsOfService(businessInfo: BusinessInfo): DocumentTemplate {
    const content = `
# Terms of Service for ${businessInfo.organizationName}

**Effective Date:** ${new Date().toLocaleDateString()}

## 1. Acceptance of Terms

By accessing and using the services provided by ${businessInfo.organizationName} ("Company," "we," "us," or "our"), you accept and agree to be bound by these Terms of Service ("Terms").

## 2. Description of Service

${businessInfo.organizationName} provides ${businessInfo.description} in the ${businessInfo.industry} industry. Our services are subject to these Terms and any additional terms and conditions that may apply to specific features or services.

## 3. User Accounts

### Account Creation
- You must provide accurate and complete information when creating an account
- You are responsible for maintaining the confidentiality of your account credentials
- You must notify us immediately of any unauthorized use of your account

### Account Responsibilities
- You are responsible for all activities that occur under your account
- You must not share your account credentials with others
- You must use our services in compliance with all applicable laws and regulations

## 4. Acceptable Use

You agree not to use our services to:
- Violate any applicable laws or regulations
- Infringe on the rights of others
- Transmit harmful, offensive, or inappropriate content
- Interfere with or disrupt our services or servers
- Attempt to gain unauthorized access to our systems

## 5. Intellectual Property

### Our Content
All content, features, and functionality of our services are owned by ${businessInfo.organizationName} and are protected by copyright, trademark, and other intellectual property laws.

### User Content
You retain ownership of content you submit to our services, but grant us a license to use, modify, and display such content in connection with providing our services.

## 6. Payment Terms

### Fees and Billing
- Fees for our services are described in our pricing pages
- All fees are non-refundable unless otherwise specified
- We may change our fees at any time with notice to users

### Payment Processing
- Payments are processed through secure third-party payment processors
- You authorize us to charge your selected payment method for all fees

## 7. Privacy

Your privacy is important to us. Please review our Privacy Policy, which governs how we collect, use, and protect your information.

## 8. Disclaimers and Limitations

### Service Availability
- Our services are provided "as is" without warranties of any kind
- We do not guarantee uninterrupted or error-free service
- We reserve the right to modify or discontinue services at any time

### Limitation of Liability
To the maximum extent permitted by law, ${businessInfo.organizationName} shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of our services.

## 9. Indemnification

You agree to indemnify and hold harmless ${businessInfo.organizationName} from any claims, damages, or expenses arising out of your use of our services or violation of these Terms.

## 10. Termination

We may suspend or terminate your account at any time for violation of these Terms. You may terminate your account at any time by contacting us.

## 11. Governing Law

These Terms are governed by the laws of ${businessInfo.state === 'DE' ? 'Delaware' : businessInfo.state}, without regard to conflict of law principles.

## 12. Changes to Terms

We may update these Terms from time to time. We will notify you of any material changes by posting the updated Terms on our website.

## 13. Contact Information

If you have any questions about these Terms, please contact us at:

**${businessInfo.organizationName}**
Email: ${businessInfo.founderEmail}

---

*These terms of service were generated by Maverick's legal document system and should be reviewed by a qualified attorney to ensure compliance with applicable laws and regulations.*
`

    return {
      type: 'terms-of-service',
      title: `Terms of Service - ${businessInfo.organizationName}`,
      content,
      lastUpdated: new Date()
    }
  }

  static generateOperatingAgreement(businessInfo: BusinessInfo): DocumentTemplate {
    if (businessInfo.organizationType !== 'LLC') {
      throw new Error('Operating Agreement is only applicable for LLC entities')
    }

    const content = `
# Operating Agreement for ${businessInfo.organizationName}

**Formation Date:** ${businessInfo.formationDate?.toLocaleDateString() || new Date().toLocaleDateString()}
**State of Formation:** ${businessInfo.state}

## 1. Formation and Purpose

### 1.1 Formation
${businessInfo.organizationName} ("Company") is a Limited Liability Company formed under the laws of ${businessInfo.state}.

### 1.2 Purpose
The purpose of the Company is to engage in ${businessInfo.description} and any other lawful business activities.

## 2. Members and Membership Interests

### 2.1 Initial Member
The initial member of the Company is:
- **Name:** ${businessInfo.founderName}
- **Email:** ${businessInfo.founderEmail}
- **Initial Membership Interest:** 100%

### 2.2 Additional Members
Additional members may be admitted to the Company only with the unanimous consent of all existing members.

## 3. Management

### 3.1 Member-Managed
The Company shall be managed by its members in proportion to their membership interests.

### 3.2 Management Powers
Members shall have the authority to:
- Make ordinary business decisions
- Enter into contracts on behalf of the Company
- Hire employees and contractors
- Open bank accounts and conduct financial transactions

## 4. Capital Contributions

### 4.1 Initial Contributions
Each member's initial capital contribution shall be as agreed upon by the members.

### 4.2 Additional Contributions
No member shall be required to make additional capital contributions without their consent.

## 5. Distributions

### 5.1 Distribution Rights
Distributions shall be made to members in proportion to their membership interests.

### 5.2 Tax Distributions
The Company may make distributions to members to cover their tax obligations related to Company income.

## 6. Books and Records

### 6.1 Maintenance
The Company shall maintain proper books and records of its business and financial affairs.

### 6.2 Member Access
Members shall have reasonable access to Company books and records.

## 7. Transfer of Membership Interests

### 7.1 Restrictions
No member may transfer their membership interest without the prior written consent of all other members.

### 7.2 Right of First Refusal
Before transferring any membership interest to a third party, the transferring member must first offer such interest to the existing members.

## 8. Dissolution

### 8.1 Events of Dissolution
The Company shall be dissolved upon:
- Unanimous consent of all members
- Entry of a decree of judicial dissolution
- Any other event that makes it unlawful to continue the Company's business

### 8.2 Winding Up
Upon dissolution, the Company's affairs shall be wound up and its assets distributed in accordance with applicable law.

## 9. Miscellaneous

### 9.1 Governing Law
This Agreement shall be governed by the laws of ${businessInfo.state}.

### 9.2 Amendment
This Agreement may be amended only by the unanimous written consent of all members.

### 9.3 Severability
If any provision of this Agreement is deemed invalid or unenforceable, the remaining provisions shall remain in full force and effect.

**IN WITNESS WHEREOF**, the undersigned has executed this Operating Agreement as of the date first written above.

**MEMBER:**

_________________________________
${businessInfo.founderName}
Member

---

*This operating agreement was generated by Maverick's legal document system and should be reviewed and customized by a qualified attorney to ensure compliance with applicable laws and specific business needs.*
`

    return {
      type: 'operating-agreement',
      title: `Operating Agreement - ${businessInfo.organizationName}`,
      content,
      lastUpdated: new Date()
    }
  }

  static generateArticlesOfIncorporation(businessInfo: BusinessInfo): DocumentTemplate {
    if (businessInfo.organizationType === 'LLC') {
      throw new Error('Articles of Incorporation are not applicable for LLC entities. Use Articles of Organization instead.')
    }

    const content = `
# Articles of Incorporation for ${businessInfo.organizationName}

**Filed with the Secretary of State of ${businessInfo.state}**

## Article I - Name
The name of the corporation is ${businessInfo.organizationName}.

## Article II - Purpose
The purpose of the corporation is to engage in ${businessInfo.description} and any other lawful business activities permitted under the laws of ${businessInfo.state}.

## Article III - Registered Office and Agent
The address of the registered office and the name of the registered agent are as follows:
[To be completed upon formation]

## Article IV - Capital Stock

### 4.1 Authorized Shares
The corporation is authorized to issue ${businessInfo.organizationType === 'S-Corp' ? '10,000,000' : '100,000,000'} shares of common stock, par value $0.001 per share.

### 4.2 Classes of Stock
${businessInfo.organizationType === 'C-Corp' ? 
  'The corporation may issue multiple classes of stock with different rights, preferences, and restrictions as determined by the Board of Directors.' :
  'The corporation is authorized to issue only one class of common stock.'
}

## Article V - Board of Directors

### 5.1 Initial Directors
The number of directors constituting the initial board of directors is one (1), and the name and address of the initial director is:

**Name:** ${businessInfo.founderName}
**Address:** [To be provided]

### 5.2 Director Powers
The board of directors shall have the authority to manage the business and affairs of the corporation.

## Article VI - Incorporator
The name and address of the incorporator is:

**Name:** ${businessInfo.founderName}
**Address:** [To be provided]

## Article VII - Duration
The corporation shall exist perpetually unless dissolved in accordance with the laws of ${businessInfo.state}.

## Article VIII - Liability
No director or officer of the corporation shall be personally liable to the corporation or its shareholders for monetary damages for breach of fiduciary duty as a director or officer, except for liability:
- For acts or omissions that involve intentional misconduct or a knowing violation of law
- For improper personal benefit from the corporation
- For acts or omissions occurring prior to the date this provision becomes effective

## Article IX - Indemnification
The corporation shall indemnify its directors, officers, employees, and agents to the fullest extent permitted by the laws of ${businessInfo.state}.

**IN WITNESS WHEREOF**, the undersigned incorporator has executed these Articles of Incorporation.

_________________________________
${businessInfo.founderName}
Incorporator

Date: ${new Date().toLocaleDateString()}

---

*These articles of incorporation were generated by Maverick's legal document system and must be filed with the appropriate state agency. This document should be reviewed and customized by a qualified attorney to ensure compliance with state requirements and specific business needs.*
`

    return {
      type: 'articles-of-incorporation',
      title: `Articles of Incorporation - ${businessInfo.organizationName}`,
      content,
      lastUpdated: new Date()
    }
  }

  static generateAllDocuments(businessInfo: BusinessInfo): DocumentTemplate[] {
    const documents: DocumentTemplate[] = []

    // Always generate privacy policy and terms of service
    documents.push(this.generatePrivacyPolicy(businessInfo))
    documents.push(this.generateTermsOfService(businessInfo))

    // Generate entity-specific documents
    if (businessInfo.organizationType === 'LLC') {
      documents.push(this.generateOperatingAgreement(businessInfo))
    } else {
      documents.push(this.generateArticlesOfIncorporation(businessInfo))
    }

    return documents
  }

  static exportToMarkdown(document: DocumentTemplate): string {
    return `---
title: ${document.title}
type: ${document.type}
lastUpdated: ${document.lastUpdated.toISOString()}
---

${document.content}
`
  }

  static exportToPDF(document: DocumentTemplate): Buffer {
    // This would require a PDF generation library like puppeteer or jsPDF
    // For now, return a placeholder
    throw new Error('PDF export not yet implemented. Use Markdown export instead.')
  }
}

// Helper function to validate business information
export function validateBusinessInfo(businessInfo: Partial<BusinessInfo>): string[] {
  const errors: string[] = []

  if (!businessInfo.organizationName) errors.push('Organization name is required')
  if (!businessInfo.organizationType) errors.push('Organization type is required')
  if (!businessInfo.state) errors.push('State is required')
  if (!businessInfo.founderName) errors.push('Founder name is required')
  if (!businessInfo.founderEmail) errors.push('Founder email is required')
  if (!businessInfo.industry) errors.push('Industry is required')
  if (!businessInfo.description) errors.push('Business description is required')

  // Validate email format
  if (businessInfo.founderEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(businessInfo.founderEmail)) {
    errors.push('Invalid email format')
  }

  return errors
}