name: Deploy to Azure App Service (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create Azure Container Registry if not exists
      run: |
        az acr create --resource-group maverick_group --name maverickacr --sku Basic --location centralus || echo "Registry already exists"
    
    - name: Login to Azure Container Registry
      run: |
        az acr login --name maverickacr
    
    - name: Build and push Docker image to ACR
      run: |
        docker build -t maverickacr.azurecr.io/maverick:latest .
        docker push maverickacr.azurecr.io/maverick:latest
    
    - name: Deploy container to App Service
      run: |
        # Configure App Service to use ACR image
        az webapp config container set \
          --name maverick \
          --resource-group maverick_group \
          --docker-custom-image-name maverickacr.azurecr.io/maverick:latest \
          --docker-registry-server-url https://maverickacr.azurecr.io
        
        # Restart the app to pull the new image
        az webapp restart --name maverick --resource-group maverick_group
    
    - name: Verify deployment  
      run: |
        echo "🚀 Docker deployment completed!"
        echo "App URL: https://maverick-fcendrb4gte0dnf5.centralus-01.azurewebsites.net"
        echo "Waiting 60 seconds for container startup..."
        sleep 60
        curl -I https://maverick-fcendrb4gte0dnf5.centralus-01.azurewebsites.net/ || echo "Container still starting up"