name: Deploy to Azure App Service (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t maverick:latest .
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Docker container to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'maverick'
        images: 'maverick:latest'
    
    - name: Verify deployment  
      run: |
        echo "🚀 Docker deployment completed!"
        echo "App URL: https://maverick-fcendrb4gte0dnf5.centralus-01.azurewebsites.net"
        echo "Waiting 60 seconds for container startup..."
        sleep 60
        curl -I https://maverick-fcendrb4gte0dnf5.centralus-01.azurewebsites.net/ || echo "Container still starting up"