name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: maverick-prod
        resourceGroup: maverick-rg
        imageToBuild: '.'
        dockerfilePath: Dockerfile
        targetPort: 5001
        ingress: external
        environmentVariables: |
          NODE_ENV=production
          NEXTAUTH_URL=https://flywithmaverick.com
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}
          AZURE_EMAIL_CONNECTION_STRING=${{ secrets.AZURE_EMAIL_CONNECTION_STRING }}