# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - maverick

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: |
          # Clean install with fresh lockfile if needed
          rm -f package-lock.json
          npm install

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: List build artifacts (debug)
        run: |
          echo "Checking .next directory:"
          ls -la .next/ || echo ".next directory not found!"
          echo "Checking root directory:"
          ls -la

      - name: Prepare deployment package
        run: |
          # Remove node_modules to save space and avoid conflicts
          rm -rf node_modules
          # Create a clean deployment package
          echo "Final package contents:"
          ls -la

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !node_modules
            !coverage
            !.git

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Verify deployment package (debug)
        run: |
          echo "=== Deployment package contents ==="
          ls -la
          echo "=== Checking for .next directory ==="
          ls -la .next/ || echo ".next directory missing in deployment package!"
          echo "=== Total package size ==="
          du -sh .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A40E1068DD244D21A83F1020AA1406DC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AB55E2B457C44CC9A53E1F220838A0F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2FDD79C1286245E38F07B5D998099557 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'maverick'
          slot-name: 'Production'
          package: .
          startup-command: './startup.sh'
          